# Generated by Django 2.0.6 on 2020-04-10 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', 'activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_temp',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='min_temp',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
