# Generated by Django 2.2.10 on 2020-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_auto_20200410_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_wind',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_wind',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_temp',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_temp',
            field=models.IntegerField(default=70),
        ),
    ]
